### ISSUE TITLE
Enable update filtering with allowed_updates

### ISSUE THREAD

**Issue by BjoernPetersen** [yi-jiayu/terraform-provider-telegram#7]
The [`setWebhook` method](https://core.telegram.org/bots/api#setwebhook) allows setting an array with the allowed update types for the bot. It would be nice to expose those in the `telegram_bot_webhook` resource.

**Comment by yi-jiayu** [comment]
Thanks for the suggestion! I didn't add it before because I didn't use it, but I'll try to get around to doing it.

**Comment by yi-jiayu** [comment]
This has been implemented in https://github.com/yi-jiayu/terraform-provider-telegram/commit/f3dd86a90891bc5d697f72743728b17041bad20f and released in [v0.2.0](https://github.com/yi-jiayu/terraform-provider-telegram/releases/tag/v0.2.0). The [documentation](https://github.com/yi-jiayu/terraform-provider-telegram/blob/f3dd86a90891bc5d697f72743728b17041bad20f/website/docs/r/bot_webhook.html.markdown) for telegram_bot_webhook has been updated.

**Comment by BjoernPetersen** [comment]
Thanks, that was way faster than expected!
