### ISSUE TITLE
Build for darwin_arm64

### ISSUE THREAD

**Issue by TeaDove** [yi-jiayu/terraform-provider-telegram#9]
Trying to use this provider raises error on Apple Silicon:

```
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/yi-jiayu/telegram v0.2.1 does not have a
│ package available for your current platform, darwin_arm64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all
│ providers are available for all platforms. Other versions of this provider
│ may have different platforms supported.
```

**Comment by yi-jiayu** [comment]
Thanks for pointing this out! Upgraded to terraform-plugin-sdk v2 and updated the release configuration, v0.3.1 should support Apple Silicon: https://registry.terraform.io/providers/yi-jiayu/telegram/0.3.1

**Comment by TeaDove** [comment]
@yi-jiayu 
Thank you!

0.3.1 work perfectly fine on Apple Silicone!
